Repository wirecard/prestashop-ee, pull requests merged in 2019-01, with the labels that each got.

#97 Add Prestashop validator test to CI
  .bin/generate-release-package.sh
  .bin/process-validator-report.py
  .bin/run-validator-test.sh
  .bin/version-helper.php
  .travis.yml
  phpcs.xml
  phpunit.xml
  wirecardpaymentgateway/codeception.yml
  wirecardpaymentgateway/tests/_support/AcceptanceTester.php
  wirecardpaymentgateway/tests/_support/Helper/Acceptance.php
  wirecardpaymentgateway/tests/acceptance.suite.yml
  wirecardpaymentgateway/tests/acceptance/TestValidatorCest.php
Labels: ready for merge

#96 Phraseapp integration
  .bin/phraseapp/.editorconfig
  .bin/phraseapp/const.rb
  .bin/phraseapp/env.rb
  .bin/phraseapp/translation-builder.rb
  .bin/phraseapp/wd-git.rb
  .bin/phraseapp/wd-github.rb
  .bin/phraseapp/wd-phraseapp.rb
  .bin/phraseapp/wd-project.rb
  .bundle/config
  .gitignore
  .rubocop.yml
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  Rakefile
  wirecardpaymentgateway/models/PaymentAlipayCrossborder.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/views/templates/hook/infos.tpl
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for review

#99 Fallback language
  .bin/phraseapp/translation-builder.rb
  wirecardpaymentgateway/controllers/admin/WirecardAjax.php
  wirecardpaymentgateway/controllers/admin/WirecardSupport.php
  wirecardpaymentgateway/controllers/admin/WirecardTransactions.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/views/templates/admin/_configure/helpers/form/form.tpl
  wirecardpaymentgateway/views/templates/admin/backend/helpers/view/view.tpl
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
  wirecardpaymentgateway/views/templates/front/creditcard_submitform.tpl
  wirecardpaymentgateway/views/templates/front/ideal.tpl
  wirecardpaymentgateway/views/templates/front/invoice.tpl
  wirecardpaymentgateway/views/templates/front/payment_infos.tpl
  wirecardpaymentgateway/views/templates/front/pia.tpl
  wirecardpaymentgateway/views/templates/front/sepa_mandate.tpl
  wirecardpaymentgateway/views/templates/front/sepadirectdebit.tpl
  wirecardpaymentgateway/views/templates/hook/infos.tpl
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: work in progress

#104 Add tag generation after testing
  .travis.yml
Labels: ready for review
