Repository wirecard/prestashop-ee, pull requests merged in 2019-08, with the labels that each got.

#187 Engine processing Tpwdcee 4470
  wirecardpaymentgateway/classes/EngineResponseProcessing/EngineResponseProcessing.php
  wirecardpaymentgateway/classes/EngineResponseProcessing/NotificationPaymentEngineResponseProcessing.php
  wirecardpaymentgateway/classes/EngineResponseProcessing/PaymentEngineResponseProcessing.php
  wirecardpaymentgateway/classes/EngineResponseProcessing/ReturnPaymentEngineResponseProcessing.php
  wirecardpaymentgateway/classes/ResponseProcessing/CancelResponseProcessing.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
Labels: ready for review

#197 Return/notify unit tests TPWDCEE-4473
  Test/Stubs/Order.php
  Test/Unit/Classes/Notification/ProcessablePaymentNotificationFactoryTest.php
  Test/Unit/Classes/Response/ProcessablePaymentResponseFactoryTest.php
Labels: ready for review

#186 Phraseapp escape single quotes Tpwdcee 4371
  .bin/phraseapp/translation-builder.rb
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
Labels: ready for testing

#200 Add spinner for elements loading in UI [TPWDCEE-4315]
  wirecardpaymentgateway/models/PaymentSofort.php
  wirecardpaymentgateway/views/css/app.css
  wirecardpaymentgateway/views/img/paymenttypes/alipay-xborder.png
  wirecardpaymentgateway/views/img/paymenttypes/creditcard.png
  wirecardpaymentgateway/views/img/paymenttypes/ideal.png
  wirecardpaymentgateway/views/img/paymenttypes/masterpass.png
  wirecardpaymentgateway/views/img/paymenttypes/p24.png
  wirecardpaymentgateway/views/img/paymenttypes/paypal.png
  wirecardpaymentgateway/views/img/paymenttypes/sepadirectdebit.png
  wirecardpaymentgateway/views/img/paymenttypes/sofortbanking.png
  wirecardpaymentgateway/views/js/creditcard.js
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
  wirecardpaymentgateway/views/templates/front/creditcard_submitform.tpl
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for merge

#181 update test credentials validation
  composer.json
  wirecardpaymentgateway/controllers/admin/WirecardAjax.php
Labels: ready for review

#202 Quick fixes for JavaScript style issues
  wirecardpaymentgateway/views/js/creditcard.js
Labels: ready for review

#203 Re-render seamless form on submission error
  wirecardpaymentgateway/views/js/creditcard.js
Labels: ready for review
