Repository wirecard/prestashop-ee, pull requests merged in 2020-04, with the labels that each got.

#316 Change alipay xborder logo
  wirecardpaymentgateway/views/img/paymenttypes/alipay-xborder.png
Labels: ready for merge

#319 Add change release version GitHub action
  .github/workflows/change-release-version.yml
Labels: no-release, ready for approval

#318 Show error message if there is an error from WPP
  .bin/phraseapp/translation-builder.rb
  wirecardpaymentgateway/controllers/front/payment.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/PaymentErrorHelper.php
  wirecardpaymentgateway/helper/TranslationHelper.php
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/views/js/creditcard.js
Labels: ready for merge

#320 Tpwdcee 6449 feature
  CHANGELOG.md
  SHOPVERSIONS
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for approval

#322 Tpwdcee 6197 feature
  Test/Stubs/Configuration.php
  Test/Stubs/Module.php
  Test/Unit/Classes/Service/OrderStateManagerServiceTest.php
  Test/bootstrap.php
  composer.json
  wirecardpaymentgateway/classes/Config/OrderStateMappingDefinition.php
  wirecardpaymentgateway/classes/Notification/Failure.php
  wirecardpaymentgateway/classes/Notification/Initial/Success.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/ProcessType.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Success.php
  wirecardpaymentgateway/classes/Response/Success.php
  wirecardpaymentgateway/classes/Service/OrderStateManagerService.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/helper/Logger.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/OrderStateTransferObject.php
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for approval

#323 Add dependabot to PR lint
  .github/pr-labeler.yml
  .github/prlint.json
Labels: no-release

#324 Add github action to validate travis file
  .github/workflows/validate-travis-file.yml
Labels: no-release

#325 Use Wirecard GitHub action and expand PR labeler
  .github/pr-labeler.yml
  .github/workflows/change-release-version.yml
  .github/workflows/run_cs_unit_coverage.yml
Labels: no-release

#328 Update pr-labeler.yml
  .github/pr-labeler.yml
Labels: no-release

#330 Add master to allowed PR branch names
  .github/prlint.json
Labels: no-release
