Repository wirecard/prestashop-ee, pull requests merged in 2020-05, with the labels that each got.

#334 Remove SHOPVERSIONS and add compose dry run for unit tests
  .github/artifact-configuration.json
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  SHOPVERSIONS
Labels: no-release

#335 Update validate travis pipeline to run only on travis file change
  .github/workflows/validate-travis-file.yml
Labels: no-release

#326 Start of TPWDCEE-6244
  Test/Stubs/Configuration.php
  Test/Unit/Classes/Response/ProcessablePaymentResponseFactoryTest.php
  Test/Unit/Classes/Service/OrderStateManagerServiceTest.php
  Test/bootstrap.php
  composer.json
  wirecardpaymentgateway/classes/Config/OrderStateMappingDefinition.php
  wirecardpaymentgateway/classes/Finder/DbFinder.php
  wirecardpaymentgateway/classes/Finder/OrderFinder.php
  wirecardpaymentgateway/classes/Finder/TransactionFinder.php
  wirecardpaymentgateway/classes/Notification/Failure.php
  wirecardpaymentgateway/classes/Notification/Initial/Success.php
  wirecardpaymentgateway/classes/Notification/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Notification/ProcessablePaymentNotificationFactory.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Success.php
  wirecardpaymentgateway/classes/Response/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Response/ProcessablePaymentResponseFactory.php
  wirecardpaymentgateway/classes/Response/Success.php
  wirecardpaymentgateway/classes/Service/OrderAmountCalculatorService.php
  wirecardpaymentgateway/classes/Service/OrderStateManagerService.php
  wirecardpaymentgateway/classes/Service/OrderStateNumericalValues.php
  wirecardpaymentgateway/classes/Service/TransactionPostProcessingService.php
  wirecardpaymentgateway/controllers/admin/WirecardTransactions.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/helper/Logger.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/OrderStateTransferObject.php
  wirecardpaymentgateway/models/Transaction.php
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for merge

#339 Generic order-state handling of post-processing.
  Test/Stubs/Configuration.php
  Test/Unit/Classes/Service/OrderStateManagerServiceTest.php
  Test/bootstrap.php
  composer.json
  wirecardpaymentgateway/classes/Config/OrderStateMappingDefinition.php
  wirecardpaymentgateway/classes/Finder/TransactionFinder.php
  wirecardpaymentgateway/classes/Notification/Failure.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Success.php
  wirecardpaymentgateway/classes/Response/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Service/OrderAmountCalculatorService.php
  wirecardpaymentgateway/classes/Service/OrderStateManagerService.php
  wirecardpaymentgateway/classes/Service/OrderStateNumericalValues.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/OrderStateTransferObject.php
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
Labels: ready for approval

#314 Adding order number as part of request data being always sent
  Test/Stubs/Db.php
  Test/Unit/Helper/TransactionBuilderTest.php
  wirecardpaymentgateway/helper/TransactionBuilder.php
Labels: ready for approval

#338 Tpwdcee 6463 feature
  composer.json
  wirecardpaymentgateway/classes/Notification/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Success.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/Service/OrderService.php
  wirecardpaymentgateway/models/Transaction.php
Labels: ready for approval

#340 Tpwdcee 6621 feature
  README.md
  composer.json
  wirecardpaymentgateway/classes/Finder/TransactionFinder.php
  wirecardpaymentgateway/classes/Hook/BeforeOrderStatusUpdateHandler.php
  wirecardpaymentgateway/classes/Hook/OrderStatusUpdateCommand.php
  wirecardpaymentgateway/classes/Notification/Failure.php
  wirecardpaymentgateway/classes/Notification/Initial/Failure.php
  wirecardpaymentgateway/classes/Notification/PostProcessing/Failure.php
  wirecardpaymentgateway/classes/Notification/ProcessablePaymentNotificationFactory.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/ProcessablePaymentFactory.php
  wirecardpaymentgateway/classes/Response/Cancel.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Failure.php
  wirecardpaymentgateway/classes/Response/Initial/Success.php
  wirecardpaymentgateway/classes/Response/PostProcessing/Failure.php
  wirecardpaymentgateway/classes/Response/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Response/ProcessablePaymentResponseFactory.php
  wirecardpaymentgateway/classes/Response/Success.php
  wirecardpaymentgateway/classes/Service/OrderAmountCalculatorService.php
  wirecardpaymentgateway/classes/Service/OrderStateManagerService.php
  wirecardpaymentgateway/classes/Service/TabManagerService.php
  wirecardpaymentgateway/classes/Service/TransactionPossibleOperationService.php
  wirecardpaymentgateway/classes/Service/TransactionPostProcessingService.php
  wirecardpaymentgateway/classes/Transaction/Builder/Entity/Basket/BasketBuilder.php
  wirecardpaymentgateway/classes/Transaction/Builder/Entity/EntityBuilderFactory.php
  wirecardpaymentgateway/controllers/admin/WirecardAjax.php
  wirecardpaymentgateway/controllers/admin/WirecardGeneralSettings.php
  wirecardpaymentgateway/controllers/admin/WirecardTransactions.php
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/controllers/front/payment.php
  wirecardpaymentgateway/controllers/front/return.php
  wirecardpaymentgateway/helper/AdditionalInformationBuilder.php
  wirecardpaymentgateway/helper/CustomerHelper.php
  wirecardpaymentgateway/helper/DeviceIdentificationHelper.php
  wirecardpaymentgateway/helper/Form/Element/BaseElement.php
  wirecardpaymentgateway/helper/Form/Element/SwitchInput.php
  wirecardpaymentgateway/helper/Form/FormHelper.php
  wirecardpaymentgateway/helper/Logger.php
  wirecardpaymentgateway/helper/NumericHelper.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/helper/OrderStateTransferObject.php
  wirecardpaymentgateway/helper/PaymentProvider.php
  wirecardpaymentgateway/helper/Service/GeneralSettingsService.php
  wirecardpaymentgateway/helper/Service/OrderService.php
  wirecardpaymentgateway/helper/ThreeDSBuilder.php
  wirecardpaymentgateway/helper/TransactionBuilder.php
  wirecardpaymentgateway/models/Payment.php
  wirecardpaymentgateway/models/PaymentIdeal.php
  wirecardpaymentgateway/models/PaymentSepaDirectDebit.php
  wirecardpaymentgateway/models/Transaction.php
  wirecardpaymentgateway/upgrade/install-2.10.0.php
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: no-release, ready for merge

#343 Clean up travis file
  .bin/compatible-shop-releases.txt
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .travis.yml
  Dockerfile
Labels: no-release, ready for review

#342 Add partial refund and capture order payment
  Test/Stubs/Order.php
  Test/Unit/Helper/Service/OrderServiceTest.php
  wirecardpaymentgateway/classes/Notification/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/helper/Service/OrderService.php
  wirecardpaymentgateway/models/Transaction.php
Labels: ready for approval

#344 Additional filtering of backend operations based on type
  wirecardpaymentgateway/classes/Notification/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Failure.php
  wirecardpaymentgateway/classes/Service/OrderAmountCalculatorService.php
  wirecardpaymentgateway/classes/Service/OrderStateManagerService.php
  wirecardpaymentgateway/classes/Service/TransactionPossibleOperationService.php
  wirecardpaymentgateway/classes/Service/TransactionPostProcessingService.php
  wirecardpaymentgateway/controllers/front/notify.php
  wirecardpaymentgateway/models/InitialTransaction.php
  wirecardpaymentgateway/models/SettleableTransaction.php
  wirecardpaymentgateway/models/Transaction.php
Labels: ready for approval
