Repository wirecard/prestashop-ee, pull requests merged in 2020-08, with the labels that each got.

#369 Remove support of masterpass
  wirecardpaymentgateway/classes/Service/TransactionPossibleOperationService.php
  wirecardpaymentgateway/helper/PaymentProvider.php
  wirecardpaymentgateway/views/img/paymenttypes/masterpass.png
Labels: ready for testing

#368 Fix cancel button behavior in general settings.
  wirecardpaymentgateway/controllers/admin/WirecardGeneralSettings.php
Labels: work in progress

#370 Tpwdcee 6135 feature
  Test/Stubs/Db.php
  Test/Unit/Models/Payments/CreditCardVaultTest.php
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/helper/AddressHashHelper.php
  wirecardpaymentgateway/models/CreditCardVault.php
  wirecardpaymentgateway/upgrade/install-2.12.0.php
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for review

#367 RC-2.12.0-minor
  CHANGELOG.md
  Test/Stubs/Db.php
  Test/Unit/Models/Payments/CreditCardVaultTest.php
  wirecardpaymentgateway/classes/Service/TransactionPossibleOperationService.php
  wirecardpaymentgateway/controllers/admin/WirecardGeneralSettings.php
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/helper/AddressHashHelper.php
  wirecardpaymentgateway/helper/PaymentProvider.php
  wirecardpaymentgateway/models/CreditCardVault.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/upgrade/install-2.12.0.php
  wirecardpaymentgateway/views/img/paymenttypes/masterpass.png
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: minor

#372 Validate branch name
  .github/pr_lint.json
  .github/prlint.json
  .github/workflows/pr-lint.yml
Labels: no-release
