Repository wirecard/prestashop-ee, pull requests merged in 2020-03, with the labels that each got.

#293 Use shopsystem-ui-testsuite project for UI tests
  .bin/process-validator-report.py
  .bin/run-ui-tests.sh
  .bin/run-validator-test.sh
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .bin/upload-logs-and-notify.sh
  .env
  .travis.yml
  Dockerfile
  Dockerfile_codeception
  docker-compose.yml
  wirecardpaymentgateway/tests/_data/CustomerData.json
  wirecardpaymentgateway/tests/_data/PaymentMethodData.json
  wirecardpaymentgateway/tests/_data/configure_payment_method_db.php
  wirecardpaymentgateway/tests/_data/gateway_configs/creditcard.json
  wirecardpaymentgateway/tests/_data/gateway_configs/paypal.json
  wirecardpaymentgateway/tests/_support/AcceptanceTester.php
  wirecardpaymentgateway/tests/_support/ActorExtendedWithWrappers.php
  wirecardpaymentgateway/tests/_support/Helper/Acceptance.php
  wirecardpaymentgateway/tests/_support/Helper/DbHelper.php
  wirecardpaymentgateway/tests/_support/Page/Base.php
  wirecardpaymentgateway/tests/_support/Page/Checkout.php
  wirecardpaymentgateway/tests/_support/Page/OrderReceived.php
  wirecardpaymentgateway/tests/_support/Page/PayPalLogIn.php
  wirecardpaymentgateway/tests/_support/Page/PayPalReview.php
  wirecardpaymentgateway/tests/_support/Page/Product.php
  wirecardpaymentgateway/tests/_support/Page/Shop.php
  wirecardpaymentgateway/tests/_support/Page/Verified.php
  wirecardpaymentgateway/tests/acceptance.suite.yml
  wirecardpaymentgateway/tests/acceptance/1-PayPalPurchaseHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/2-PayPalAuthorizationHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/3-CreditCardNon3DSPurchaseHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/4-CreditCard3DSAuthorizationHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/5-CreditCard3DSOneClickHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/6-CreditCard3DSPurchaseHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/TestValidatorCest.php
Labels: ready for testing

#287 Fix wrong final order state in different payment methods
  wirecardpaymentgateway/classes/Notification/Initial/Success.php
  wirecardpaymentgateway/classes/Notification/PostProcessing/Success.php
  wirecardpaymentgateway/classes/Notification/Success.php
  wirecardpaymentgateway/classes/Response/Success.php
  wirecardpaymentgateway/helper/Service/OrderService.php
Labels: ready for testing

#295 Fix number format to show without comma separator
  wirecardpaymentgateway/views/templates/admin/backend/helpers/view/view.tpl
Labels: ready for review

#299 Use master branch of ui-test-project
  .bin/run-ui-tests.sh
Labels: ready for review

#296 Add phrase keys
  Test/Stubs/OrderState.php
  wirecardpaymentgateway/helper/OrderManager.php
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for merge

#300 Remove update of version file
  .travis.yml
Labels: no-release

#302 Remove unused variable
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: ready for approval

#301 Bump release version
  CHANGELOG.md
  SHOPVERSIONS
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: minor

#307 Update readme documentation
  README.md
Labels: no-release

#308 Substitute hardcoded prefix table
  .github/workflows/run_cs_unit_coverage.yml
  wirecardpaymentgateway/classes/Finder/TransactionFinder.php
Labels: ready for review

#310 Offer vault only for non-guests
  wirecardpaymentgateway/models/Payment.php
  wirecardpaymentgateway/models/PaymentCreditCard.php
Labels: ready for merge

#311 Disable 'select card' button by default and activate when necessary
  wirecardpaymentgateway/views/js/creditcard.js
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
Labels: ready for merge

#312 Tpwdcee 5427 feature
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/views/js/creditcard.js
Labels: ready for merge

#305 Initial commit for RC 2.9.0
  .github/workflows/run_cs_unit_coverage.yml
  CHANGELOG.md
  SHOPVERSIONS
  Test/Unit/Classes/Transaction/Builder/PostProcessingTransactionBuilderTest.php
  Test/Unit/Helper/Form/Element/SwitchInputTest.php
  Test/Unit/Helper/Form/FormHelperTest.php
  Test/Unit/Helper/TemplateHelperTest.php
  Test/Unit/WirecardPaymentGatewayTest.php
  Test/bootstrap.php
  composer.json
  wirecardpaymentgateway/classes/Config/Credentials/CredentialsConfiguration.php
  wirecardpaymentgateway/classes/Finder/TransactionFinder.php
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/credentials_config.xml
  wirecardpaymentgateway/models/Payment.php
  wirecardpaymentgateway/models/PaymentAlipayCrossborder.php
  wirecardpaymentgateway/models/PaymentCreditCard.php
  wirecardpaymentgateway/models/PaymentGuaranteedInvoiceRatepay.php
  wirecardpaymentgateway/models/PaymentIdeal.php
  wirecardpaymentgateway/models/PaymentPaypal.php
  wirecardpaymentgateway/models/PaymentPoiPia.php
  wirecardpaymentgateway/models/PaymentPtwentyfour.php
  wirecardpaymentgateway/models/PaymentSepaCreditTransfer.php
  wirecardpaymentgateway/models/PaymentSepaDirectDebit.php
  wirecardpaymentgateway/models/PaymentSofort.php
  wirecardpaymentgateway/views/js/creditcard.js
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: minor

#313 Change setup-php checkout version
  .github/workflows/run_cs_unit_coverage.yml
Labels: no-release
