Repository wirecard/prestashop-ee, pull requests merged in 2020-02, with the labels that each got.

#263 Update order state to cancel on void-authorization
  wirecardpaymentgateway/models/Transaction.php
Labels: work in progress

#266 Tpwdcee 5959 force
  wirecardpaymentgateway/classes/Constants/ConfigConstants.php
  wirecardpaymentgateway/controllers/admin/WirecardSupport.php
  wirecardpaymentgateway/tests/_support/Page/PayPalReview.php
  wirecardpaymentgateway/tests/acceptance/1-PayPalPurchaseHappyPath.feature
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: no-release

#272 Switch Unit tests execution to GithubActions
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
Labels: ready for approval

#273 Add feature option to PR Lint
  .github/prlint.json
Labels: no-release

#277 Disable nightly compatibility checks
  .travis.yml
Labels: no-release, ready for approval

#278 Update CHANGELOG.md
  CHANGELOG.md
Labels: patch

#276 Display proper error message for WPP credit card failures
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/controllers/front/payment.php
  wirecardpaymentgateway/helper/Service/ContextService.php
  wirecardpaymentgateway/views/js/creditcard.js
Labels: ready for merge

#282 Add filter for wirecard transaction table
  Test/Stubs/ModuleAdminController.php
  wirecardpaymentgateway/controllers/admin/WirecardTransactions.php
Labels: ready for testing

#283 Remove unrelevant badges
  README.md
Labels: no-release

#284 Send mobile phone if customer not provided phone number
  wirecardpaymentgateway/helper/AdditionalInformationBuilder.php
Labels: ready for approval

#281 Rearrange saved credit card popup structure for mobile look improvements
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/views/css/app.css
  wirecardpaymentgateway/views/js/creditcard.js
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
  wirecardpaymentgateway/views/templates/front/creditcard_list.tpl
Labels: ready for merge

#270 Rc 2.7.0 minor
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  CHANGELOG.md
  SHOPVERSIONS
  Test/Stubs/ModuleAdminController.php
  wirecardpaymentgateway/controllers/admin/WirecardTransactions.php
  wirecardpaymentgateway/controllers/front/creditcard.php
  wirecardpaymentgateway/controllers/front/payment.php
  wirecardpaymentgateway/helper/AdditionalInformationBuilder.php
  wirecardpaymentgateway/helper/Service/ContextService.php
  wirecardpaymentgateway/models/Transaction.php
  wirecardpaymentgateway/translations/cs_CZ.php
  wirecardpaymentgateway/translations/de.php
  wirecardpaymentgateway/translations/en.php
  wirecardpaymentgateway/translations/fr.php
  wirecardpaymentgateway/translations/id.php
  wirecardpaymentgateway/translations/ja.php
  wirecardpaymentgateway/translations/ko.php
  wirecardpaymentgateway/translations/nl_NL.php
  wirecardpaymentgateway/translations/pl.php
  wirecardpaymentgateway/translations/sk_SK.php
  wirecardpaymentgateway/translations/tw.php
  wirecardpaymentgateway/translations/zh.php
  wirecardpaymentgateway/views/css/app.css
  wirecardpaymentgateway/views/js/creditcard.js
  wirecardpaymentgateway/views/js/sepadirectdebit.js
  wirecardpaymentgateway/views/templates/front/creditcard.tpl
  wirecardpaymentgateway/views/templates/front/creditcard_list.tpl
  wirecardpaymentgateway/wirecardpaymentgateway.php
Labels: minor, ready for merge

#286 Change PayPal credentials and save them as environment variables
  .bin/compatible-shop-releases.txt
  wirecardpaymentgateway/tests/_data/PaymentMethodData.json
  wirecardpaymentgateway/tests/_support/Page/PayPalLogIn.php
  wirecardpaymentgateway/tests/acceptance/1-PayPalPurchaseHappyPath.feature
  wirecardpaymentgateway/tests/acceptance/2-PayPalAuthorizationHappyPath.feature
Labels: no-release, ready for approval

#285 Fix release polling script for whitelabelling triggering
  .bin/check-release-notes-exist.sh
Labels: no-release

#291 Removed not allowed payment email fields from whitelisted array
  wirecardpaymentgateway/classes/Constants/ConfigConstants.php
Labels: ready for merge

#289 Update Licence from GPLv3 to MIT
  LICENSE
  _TERMS_OF_USE
  wirecardpaymentgateway/classes/Controller/WirecardFrontController.php
  wirecardpaymentgateway/classes/Controller/index.php
Labels: ready for merge

#290 Enable submit button on sepa mandate out of popup click
  wirecardpaymentgateway/views/js/sepadirectdebit.js
Labels: ready for merge
